#!/usr/bin/env bash

declare -a ARGS
declare -a headers
expires=3600
signHeaders=0
service=""
region=""
verbose=0
for var in "$@"; do
    if [[ "${var%=*}" = '--headers' ]]; then
        file=${var#*=}
        while IFS= read -r line; do
            headers+=("$line")
        done < ${file}
        continue
    fi
    if [[ "${var%=*}" = '--header' ]]; then
        keyValue=${var#*=}
        headers+=(${keyValue})
        continue
    fi
    if [[ "${var}" = '--signHeaders' ]]; then
        signHeaders=1
        continue
    fi
    if [[ "${var%=*}" = '--expires' ]]; then
        expires=${var#*=}
        continue
    fi
    if [[ "${var%=*}" == '--service' ]]; then
        service=${var#*=}
        continue
    fi
    if [[ "${var%=*}" == '--region' ]]; then
        region=${var#*=}
        continue
    fi
    if [[ "${var}" == "--verbose" ]]; then
        verbose=1
        continue
    fi
    ARGS+=("$var")
done

if [[ ${#ARGS[@]} < 3  || ${#ARGS[@]} > 4 ]]; then
    echo "Usage:"
    echo "    sign <url> <key> <secret> [<TimeStamp>] [--service=<service>] [--region=<region>] [--headers=<fileName>] [--header=<Key>:<Value>] [--signHeaders] [--expires=<TimeInSecs>] [--verbose] "
    echo
    echo "Note 1: TimeStamp: must be YYYYMMDD'T'hhmmsa'Z's"
    echo "        eg 20170901T230559Z"
    echo "        YYYY => Year MM => Month DD => day hh => hour mm => minute ss => second"
    exit 1
fi


url=${ARGS[0]}
key=${ARGS[1]}
secret=${ARGS[2]}
dateTime=${ARGS[3]-$(date -u +"%Y%m%dT%H%M%SZ")}

source signature
createSignature "${url}" "${key}" "${secret}" "${dateTime}" "${expires}" "${service}" "${region}" "${signHeaders}" "${verbose}" headers[@]
