#!/bin/bash

function upload {
    local file=$1
    eval file=${file}
    local s3=$2
    local accessKey=$3
    local secretKey=$4
    local verbose=$5
    local dryrun=$6

    local s3Path=${s3#s3://}
    local bucket=${s3Path%%/*}
    local path=${s3Path#*/}

    local dateSec=$(date +"%s")
    local dateString=$(date -j -u -f "%s" ${dateSec} +"%a, %d %b %Y %H:%M:%S %Z")
    local dateStamp=$(date -j -u  -f "%s" ${dateSec} +"%Y%m%dT%H%M%SZ")
    local size=$(stat -f "%z" ${file})

    local url=https://${bucket}.s3.amazonaws.com/${path}
    #declare -a headers=("Date:${dateString}" "Content-Length:${size}")
    declare -a headers=("Content-Length:${size}")

    verboseTmp=''
    if [[ "${verbose}" != "" ]]; then
        verboseTmp=/tmp/put.tmp
    fi
    echo VERBOSE: ${verboseTmp}

    local signature=$(createSignature PUT "${url}" "${accessKey}" "${secretKey}" ${dateStamp} 3600 's3' 'us-east-1' 1 "${verboseTmp}" headers[@])

    if [[ "${verbose}" != "" ]]; then
        cat ${verboseTmp} > ${verbose}
        cat - <<IntermediateValuese > ${verbose}

File:           ${file}
S3:             ${s3}
Prt:            ${s3Path}
Bucket:         ${bucket}
Path:           ${path}

dateSec:        ${dateSec}
dateString:     ${dateString}
dateStamp:      ${dateStamp}
Size:           ${size}

URL:            ${url}
signature:      ${signature}


IntermediateValuese
    echo                >> ${verbose}
    echo "UPLOAD"       >> ${verbose}
    echo "======"       >> ${verbose}
    echo "curl -o response --dump-header response.header --header \"${signature}\" --header \"Date: ${dateString}\" --header \"Content-Length: ${size}\" --header \"X-Amz-Content-SHA256: UNSIGNED-PAYLOAD\" --header \"X-Amz-Date: ${dateStamp}\" --data-binary \"@${file}\" -X PUT ${url}" >> ${verbose}
    fi

    if [[ ${dryrun} == 0 ]]; then
        curl -o response --dump-header response.header --header "${signature}" --header "Date: ${dateString}" --header "Content-Length: ${size}" --header "X-Amz-Content-SHA256: UNSIGNED-PAYLOAD" --header "X-Amz-Date: ${dateStamp}" --data-binary "@${file}" -X PUT ${url}
    fi
}

